### ISSUE TITLE
Question: Is it Ok to Separate Error Impl From Standard feature?

### ISSUE THREAD

**Issue by gluax** [DaniPopes/const-hex#11]
The `std` feature enables a few things like alloc and other things one might not need, but I'd still like the `Error` trait implemented for the Error type. Would it be ok to separate this out?

**Comment by DaniPopes** [comment]
core::error::Error is still unstable, it will be stabilized in 1.81, so "std" feature is still required for versions before that

**Comment by gluax** [comment]
Got it! Thanks for the fast response.
